export const restaurants = [
  {
    id: "r1",
    name: "Saffron Spice Kitchen",
    cuisine: "North Indian, Punjabi Thalis, Biryani",
    rating: 4.8,
    deliveryTime: "25-30 mins",
    costForTwo: "₹400",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Special Butter Chicken Thali"
  },
  {
    id: "r2",
    name: "The Dosa Darbar",
    cuisine: "South Indian, Authentic Tiffins, Filter Coffee",
    rating: 4.5,
    deliveryTime: "15-20 mins",
    costForTwo: "₹250",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Ghee Roast Masala Dosa"
  },
  {
    id: "r3",
    name: "Hyderabad Express",
    cuisine: "Nizami Biryani, Mughlai, Juicy Kebabs",
    rating: 4.7,
    deliveryTime: "35-40 mins",
    costForTwo: "₹500",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Special Mutton Dum Biryani"
  },
  {
    id: "r4",
    name: "Chai & Chaat Corner",
    cuisine: "Street Food, Spicy Snacks, Hot Samosas",
    rating: 4.2,
    deliveryTime: "10-15 mins",
    costForTwo: "₹150",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Delhi Style Samosa Chaat"
  },
  {
    id: "r5",
    name: "Shree Balaji Pure Veg",
    cuisine: "Rajasthani Churma, Shahi Paneer, Naan",
    rating: 4.6,
    deliveryTime: "30-35 mins",
    costForTwo: "₹350",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Paneer Butter Masala Combo"
  },
  {
    id: "r6",
    name: "Mithai Mahal",
    cuisine: "Indian Sweets, Desserts, Lassi",
    rating: 4.4,
    deliveryTime: "15-20 mins",
    costForTwo: "₹200",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Kesar Gulab Jamun (2 Pcs)"
  },
  {
    id: "r7",
    name: "Coastal Curry House",
    cuisine: "Goan Fish Curry, Malabar Parotta, Seafood",
    rating: 4.6,
    deliveryTime: "40-45 mins",
    costForTwo: "₹600",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Prawn Malabar Curry with Rice"
  },
  {
    id: "r8",
    name: "The Tandoor Room",
    cuisine: "Tandoori Platters, Kebabs, Rumali Roti",
    rating: 4.3,
    deliveryTime: "25-30 mins",
    costForTwo: "₹450",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Achari Paneer Tikka Platter"
  },
  {
    id: "r9",
    name: "Anna's Idli House",
    cuisine: "South Indian, Podi Idlis, Steamed Tiffins",
    rating: 4.7,
    deliveryTime: "10-15 mins",
    costForTwo: "₹180",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Ghee Guntur Podi Idli"
  },
  {
    id: "r10",
    name: "Peshawari Zaika",
    cuisine: "North Indian, Mughlai Roasts, Garlic Naan",
    rating: 4.8,
    deliveryTime: "35-40 mins",
    costForTwo: "₹550",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Slow-Cooked Dal Makhani"
  },
  {
    id: "r11",
    name: "Kolkata Roll Express",
    cuisine: "Street Food, Egg Kathi Rolls, Chicken Wraps",
    rating: 4.3,
    deliveryTime: "15-20 mins",
    costForTwo: "₹220",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Double Chicken Double Egg Roll"
  },
  {
    id: "r12",
    name: "Vrindavan Rasoi",
    cuisine: "Satvik Diet, No Onion No Garlic, Pure Veg Thalis",
    rating: 4.6,
    deliveryTime: "25-30 mins",
    costForTwo: "₹300",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Special Shahi Satvik Thali"
  },
  {
    id: "r13",
    name: "Grand Awadh Darbar",
    cuisine: "Lucknowi Biryani, Korma, Galouti Kebabs",
    rating: 4.9,
    deliveryTime: "40-45 mins",
    costForTwo: "₹700",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Awadhi Chicken Dum Biryani"
  },
  {
    id: "r14",
    name: "Punjab Da Dhaba",
    cuisine: "North Indian, Sarson Saag, Makki Roti",
    rating: 4.5,
    deliveryTime: "20-25 mins",
    costForTwo: "₹380",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Amritsari Kulcha with Chole"
  },
  {
    id: "r15",
    name: "Udupi Sri Krishna",
    cuisine: "South Indian, Rava Dosa, Mysurpa",
    rating: 4.6,
    deliveryTime: "12-18 mins",
    costForTwo: "₹200",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Mysore Masala Dosa"
  },
  {
    id: "r16",
    name: "The Kebab Factory",
    cuisine: "Mughlai, Seekh Kebabs, Tandoori Platters",
    rating: 4.4,
    deliveryTime: "30-35 mins",
    costForTwo: "₹480",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Mutton Seekh Kebab Platter"
  },
  {
    id: "r17",
    name: "Lonavala Chikki & Farsan",
    cuisine: "Snacks, Desserts, Namkeen Treats",
    rating: 4.1,
    deliveryTime: "10-15 mins",
    costForTwo: "₹120",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Premium Kaju Almond Chikki"
  },
  {
    id: "r18",
    name: "Malabar Shore",
    cuisine: "Kerala Cuisine, Appam, Coconut Curries",
    rating: 4.7,
    deliveryTime: "35-40 mins",
    costForTwo: "₹520",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Kerala Chicken Fry with Malabar Parotta"
  },
  {
    id: "r19",
    name: "Rajasthan Sweets & Meals",
    cuisine: "Rajasthani, Dal Baati Churma, Gatte ki Sabzi",
    rating: 4.5,
    deliveryTime: "30-35 mins",
    costForTwo: "₹400",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Authentic Dal Baati Churma Thali"
  },
  {
    id: "r20",
    name: "The Biryani Central",
    cuisine: "Biryani, North Indian, Raita Combos",
    rating: 4.6,
    deliveryTime: "25-30 mins",
    costForTwo: "₹450",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Lucknowi Veg Dum Biryani"
  },
  {
    id: "r21",
    name: "Delhi Chat Corner",
    cuisine: "Street Food, Pani Puri, Aloo Tikki",
    rating: 4.3,
    deliveryTime: "10-15 mins",
    costForTwo: "₹140",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Special Dahi Bhalla"
  },
  {
    id: "r22",
    name: "Madras Curry Corner",
    cuisine: "South Indian, Sambar Rice, Curd Rice",
    rating: 4.4,
    deliveryTime: "15-20 mins",
    costForTwo: "₹230",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Authentic Mini Tiffin Combo"
  },
  {
    id: "r23",
    name: "Royal Rajputana Kitchen",
    cuisine: "Rajasthani, Laal Maas, Missi Roti",
    rating: 4.8,
    deliveryTime: "40-45 mins",
    costForTwo: "₹650",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Fiery Rajasthani Laal Maas Combo"
  },
  {
    id: "r24",
    name: "Bikaneri Chatkhara",
    cuisine: "Snacks, Bikaneri Bhujia, Kachoris",
    rating: 4.2,
    deliveryTime: "12-18 mins",
    costForTwo: "₹160",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Pyaaz Kachori with Kadhi"
  },
  {
    id: "r25",
    name: "Sagar Ratna Feast",
    cuisine: "North Indian, South Indian, Deluxe Thalis",
    rating: 4.5,
    deliveryTime: "25-30 mins",
    costForTwo: "₹390",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Deluxe North Indian Paneer Thali"
  },
  {
    id: "r26",
    name: "The Clay Oven",
    cuisine: "Tandoori, North Indian, Paneer Tikka",
    rating: 4.4,
    deliveryTime: "22-28 mins",
    costForTwo: "₹420",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Tandoori Butter Soya Chaap"
  },
  {
    id: "r27",
    name: "Chettinad Spice Hub",
    cuisine: "South Indian, Spicy Chettinad, Parotta Combos",
    rating: 4.7,
    deliveryTime: "35-40 mins",
    costForTwo: "₹490",
    image: "https://unsplash.com",
    isPureVeg: false,
    featuredDish: "Spicy Chettinad Chicken Pepper Fry"
  },
  {
    id: "r28",
    name: "Ganga Pure Veg",
    cuisine: "North Indian, Chole Bhature, Chhach",
    rating: 4.6,
    deliveryTime: "15-20 mins",
    costForTwo: "₹240",
    image: "https://unsplash.com",
    isPureVeg: true,
    featuredDish: "Special Amritsari Chole Bhature"
}
];
